config/routes.rb
SampleApp::Application.routes.draw do
 
  devise_for :uzytkowniks
  resources :lista_plikow

  get "users/new"
  
  resources :lista_plikow #, :only => [:new, :create, :index]
  
=begin 
  match '/lista_plikow/', :to => 'lista_plikow#index'
  match '/lista_plikow/new', :to => 'lista_plikow#new', :as => :new_lista_plikow_path
  match '/lista_plikow/edit', :to => 'lista_plikow#edit'
=end
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

  

end

app/models/dyskusja.rb
class Dyskusja < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'	
	has_many:post
end

app/models/komentarz.rb
class Komentarz < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/plik.rb
class Plik < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_many:Wersja
	has_many:Komentarz
	
	attr_accessible :idPlik, :user_email, :projektID, :dataGodzina, :publiczny, :tylkoOdczyt, :sciezka
	mount_uploader :sciezka, PlikUploader
	
	def IdPlik
	idPlik
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:dyskusjaID, :class_name => 'Dyskusja'
end

app/models/projekt.rb
class Projekt < ActiveRecord::Base
	has_many:Dyskusja
	has_many:Wydarzenie
	has_many:Plik
end

app/models/udostepnianie.rb
class Udostepnianie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :imie, :nazwisko
	has_many:Dyskusja
	has_many:Komentarz
	has_many:Plik
	has_many:Udostepnianie
	has_many:Wersja
	has_many:Wiadomosc
	has_many:Wydarzenie
	has_many:Post
end

app/models/wersja.rb
class Wersja < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/wiadomosc.rb
class Wiadomosc < ActiveRecord::Base
	has_one:nadawca, :class_name => 'Uzytkownik'
	has_one:odbiorca, :class_name => 'Uzytkownik'
end

app/models/wydarzenie.rb
class Wydarzenie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dyskusje_controller.rb
class DyskusjeController < ApplicationController
end

app/controllers/projekt_controller.rb
class ProjektController < ApplicationController

  def index
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/uzytkownik_controller.rb
class UzytkownikController::RegistrationsController < Devise::RegistrationsController
layout :custom


end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/dyskusje_helper.rb
module DyskusjeHelper
end

app/helpers/lista_plikow_helper.rb
module ListaPlikowHelper
end

app/helpers/projekt_helper.rb
module ProjektHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uzytkownik_helper.rb
module UzytkownikHelper
end

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>


     <!-- Button to trigger modal -->
    <a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
    </div>
    <div class="modal-body">
    <p>One fine body…</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
    </div>
    </div>

app/views/static_pages/home.html.erb
<div class="hero-unit">
  <h1>Powrót dekodera</h1>

  <h2>
    This is the home page for the
    <a href="http://modanasuknie.blox.pl/">dekodery </a>
    sample application.

  </h2>
  


  <%= link_to "Sign up now!", new_uzytkownik_registration_path, class: "btn btn-large btn-primary" %>
</div>

<%#=link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>