config/routes.rb
SampleApp::Application.routes.draw do
 
  devise_for :uzytkowniks
  resources :lista_plikow

  get "users/new"
  
  resources :lista_plikow #, :only => [:new, :create, :index]
  
=begin 
  match '/lista_plikow/', :to => 'lista_plikow#index'
  match '/lista_plikow/new', :to => 'lista_plikow#new', :as => :new_lista_plikow_path
  match '/lista_plikow/edit', :to => 'lista_plikow#edit'
=end
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

  

end

app/models/dyskusja.rb
class Dyskusja < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'	
	has_many:post
end

app/models/komentarz.rb
class Komentarz < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/plik.rb
class Plik < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_many:Wersja
	has_many:Komentarz
	
	attr_accessible :idPlik, :user_email, :projektID, :dataGodzina, :publiczny, :tylkoOdczyt, :sciezka
	mount_uploader :sciezka, PlikUploader
	
	def IdPlik
	idPlik
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:dyskusjaID, :class_name => 'Dyskusja'
end

app/models/projekt.rb
class Projekt < ActiveRecord::Base
	has_many:Dyskusja
	has_many:Wydarzenie
	has_many:Plik
end

app/models/udostepnianie.rb
class Udostepnianie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :imie, :nazwisko
	has_many:Dyskusja
	has_many:Komentarz
	has_many:Plik
	has_many:Udostepnianie
	has_many:Wersja
	has_many:Wiadomosc
	has_many:Wydarzenie
	has_many:Post
end

app/models/wersja.rb
class Wersja < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/wiadomosc.rb
class Wiadomosc < ActiveRecord::Base
	has_one:nadawca, :class_name => 'Uzytkownik'
	has_one:odbiorca, :class_name => 'Uzytkownik'
end

app/models/wydarzenie.rb
class Wydarzenie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'
end

app/controllers/dyskusje_controller.rb
class DyskusjeController < ApplicationController
end

app/controllers/projekt_controller.rb
class ProjektController < ApplicationController

  def index
  end
  
end

app/controllers/uzytkownik_controller.rb
class UzytkownikController::RegistrationsController < Devise::RegistrationsController
layout :custom


end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/dyskusje_helper.rb
module DyskusjeHelper
end

app/helpers/lista_plikow_helper.rb
module ListaPlikowHelper
end

app/helpers/projekt_helper.rb
module ProjektHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uzytkownik_helper.rb
module UzytkownikHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Pliki",   lista_plikow_index_path %></li>

          
		  <li class="dropdown">     
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">	<i class="icon-user icon-white"></i>
			  <% if uzytkownik_signed_in? %>
			<%= current_uzytkownik.email %>
						  <% else %> niezalogowano

<% end %>
			
			
			</a>
			<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
				<li><%= link_to "Sign in", new_uzytkownik_session_path %></li>
		  <li><%= link_to "Sign out", destroy_uzytkownik_session_path, :method => :delete %></li>
			</ul>
		  </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
   <ul class="nav nav-list">
    <li class="nav-header">List header</li>
    <li class="active"><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
	<li><a href="#">Library</a></li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
	<div class="navbar navbar-fixed-top">
    <%= render 'layouts/header' %>
	</div>

    <div class="container-fluid">


	   <div class="span3">
			<%= render 'layouts/sidebar' %>
	   </div>
	 <div class="span9"><%= yield %></div>
	 
	 	<div class="navbar navbar-fixed-bottom">
      <%= render 'layouts/footer' %>
	  	 	<div class="navbar navbar-fixed-bottom">
    </div>
  </body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <div class="container-fluid">


	   <div class="span3">
			<%= render 'layouts/sidebar' %>
	   </div>
	 <div class="span9"><%= yield %></div>
	 
    </div>
  </body>
</html>