config/routes.rb
SampleApp::Application.routes.draw do
 
  devise_for :uzytkowniks
  resources :lista_plikow

  get "users/new"
  
  resources :lista_plikow #, :only => [:new, :create, :index]
  
=begin 
  match '/lista_plikow/', :to => 'lista_plikow#index'
  match '/lista_plikow/new', :to => 'lista_plikow#new', :as => :new_lista_plikow_path
  match '/lista_plikow/edit', :to => 'lista_plikow#edit'
=end
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

  

end

app/models/dyskusja.rb
class Dyskusja < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'	
	has_many:post
end

app/models/komentarz.rb
class Komentarz < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/plik.rb
class Plik < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_many:Wersja
	has_many:Komentarz
	
	attr_accessible :idPlik, :user_email, :projektID, :dataGodzina, :publiczny, :tylkoOdczyt, :sciezka
	mount_uploader :sciezka, PlikUploader
	
	def IdPlik
	idPlik
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:dyskusjaID, :class_name => 'Dyskusja'
end

app/models/projekt.rb
class Projekt < ActiveRecord::Base
	has_many:Dyskusja
	has_many:Wydarzenie
	has_many:Plik
end

app/models/udostepnianie.rb
class Udostepnianie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :imie, :nazwisko
	has_many:Dyskusja
	has_many:Komentarz
	has_many:Plik
	has_many:Udostepnianie
	has_many:Wersja
	has_many:Wiadomosc
	has_many:Wydarzenie
	has_many:Post
end

app/models/wersja.rb
class Wersja < ActiveRecord::Base
	has_one:autor, :class_name => 'Uzytkownik'
	has_one:plikID, :class_name => 'Plik'
end

app/models/wiadomosc.rb
class Wiadomosc < ActiveRecord::Base
	has_one:nadawca, :class_name => 'Uzytkownik'
	has_one:odbiorca, :class_name => 'Uzytkownik'
end

app/models/wydarzenie.rb
class Wydarzenie < ActiveRecord::Base
	has_one:user_email, :class_name => 'Uzytkownik'
	has_one:projektID, :class_name => 'Projekt'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dyskusje_controller.rb
class DyskusjeController < ApplicationController
end

app/controllers/lista_plikow_controller.rb
class ListaPlikowController < ApplicationController

  # GET /pliki
  # GET /pliki.json
  
  def index
    @pliki = Plik.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pliki }
    end
  end

  # GET /pliki/1
  # GET /pliki/1.json
  def show
    @plik = Plik.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plik }
    end
  end

  # GET /pliki/new
  # GET /pliki/new.json
  def new
    @plik = Plik.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plik }
    end
  end

  # GET /pliki/1/edit
  def edit
    @plik = Plik.find(params[:id])
  end

  # POST /pliki
  # POST /pliki.json
  def create
    @plik = Plik.new(params[:plik])

    respond_to do |format|
      if @plik.save
        format.html { redirect_to lista_plikow_path(@plik), notice: 'Plik was successfully created.' }
        format.json { render json: @plik, status: :created, location: @plik }
      else
        format.html { render action: "new" }
        format.json { render json: @plik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pliki/1
  # PUT /pliki/1.json
  def update
    @plik = Plik.find(params[:id])

    respond_to do |format|
      if @plik.update_attributes(params[:plik])
        format.html { redirect_to @plik, notice: 'Plik was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pliki/1
  # DELETE /pliki/1.json
  def destroy
    @plik = Plik.find(params[:id])
    @plik.destroy

    respond_to do |format|
      format.html { redirect_to lista_plikow_index_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/projekt_controller.rb
class ProjektController < ApplicationController

  def index
  end
  
end

app/controllers/uzytkownik_controller.rb
class UzytkownikController::RegistrationsController < Devise::RegistrationsController
layout :custom


end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/dyskusje_helper.rb
module DyskusjeHelper
end

app/helpers/lista_plikow_helper.rb
module ListaPlikowHelper
end

app/helpers/projekt_helper.rb
module ProjektHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/uzytkownik_helper.rb
module UzytkownikHelper
end

app/views/lista_plikow/_form.html.erb
<%= form_for @plik,:url=>{ :controller=>"lista_plikow", :action=>"create"}, :html => {:multipart => true} do |f| %>
  <% if @plik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plik.errors.count, "error") %> prohibited this plik from being saved:</h2>

      <ul>
      <% @plik.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label 'sciezka' %><br />
    <%= f.file_field :sciezka %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lista_plikow/edit.html.erb
<h1>Editing test2</h1>

<%= render 'form' %>

<%= link_to 'Show', lista_plikow_path(@plik) %> |
<%= link_to 'Back', lista_plikow_index_path %>

app/views/lista_plikow/index.html.erb
<h1>Uploadowanie plików</h1>

<table>
  <tr>   
    <th>Sciezka</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pliki.each do |plik| %>
<% mojString = plik.sciezka %>
  <tr>    
    <td><%= mojString %></td>
    <td><%= link_to 'Show', lista_plikow_path(plik), :method=>:get %></td>
    <td><%= link_to 'Edit', edit_lista_plikow_path(plik) %></td>
    <td><%= link_to 'Destroy', lista_plikow_path(plik), confirm: 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'dodaj nowy plik', new_lista_plikow_path %>

app/views/lista_plikow/new.html.erb
<h1>Dodaj nowy plik</h1>

<%= render 'form' %>

<%= link_to 'Back', lista_plikow_index_path %>

app/views/lista_plikow/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id Pliku:</b>
  <%= @plik.IdPlik %>
</p>

<p>
  <b>Scieżka:</b>
  <%= @plik.sciezka_url %>
</p>


<%= link_to 'Edit', edit_lista_plikow_path(@plik) %> |
<%= link_to 'Back', lista_plikow_index_path %>